### ISSUE TITLE
New fps typed not saved

### ISSUE THREAD

**Issue by Bouh** [Entr0py404/GDev-Asset-Store-Tool#3]
When we type a new value directly in the input then click save the change are not saved.
Its saved only by using arrows on the keyboard to change the values.

Here a GIF with the typed value.
![test](https://github.com/Entr0py404/GDev-Asset-Store-Tool/assets/1670670/ce7f20d2-6836-4882-b535-8c6f8c87bb65)

**Comment by Entr0py404** [comment]
If manually entering a value you would need to press return, I can improve on this by auto setting the value when the ui element loses focus and not make the sound on pressing return
