### ISSUE TITLE
The description for the template object is optionnal

### ISSUE THREAD

**Issue by Bouh** [Entr0py404/GDev-Asset-Store-Tool#4]
The tool require a description to generate the json but the description in the asset.json are optionnal. 

Also most of the buttons have the same description in the engine, there is nothing much more to tell that the button is interactive.
Is a default description in the tool can be used at least for buttons? 
The description used in the store is:
```JS
  "description": "A button that can be clicked. The background images and text can be edited.\n\nThis button provides conditions and actions for an easy use.",
```

**Comment by Entr0py404** [comment]
i will make these changes
